events {}

http {
    server {
        listen 8080;

        location /steeple/ {
            proxy_pass http://steeple-sse-nginx:8080/;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Prefix /steeple;
        }
    }
}
