--liquibase formatted sql

-- Discovery schema for Steeple. Hand-maintained SQL is the source of truth; it was bootstrapped
-- from the EF Core model (`dotnet ef migrations script`) so the kept EF entity mappings still match
-- column-for-column. Tables are snake_case; columns are quoted PascalCase to match the EF mapping.

--changeset steeple:001-schema
CREATE TABLE analytics_events (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EventType" character varying(100) NOT NULL,
    "OccurredAtUtc" timestamp with time zone NOT NULL,
    "SessionId" character varying(100),
    "PayloadJson" text,
    CONSTRAINT "PK_analytics_events" PRIMARY KEY ("Id")
);

CREATE TABLE venues (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(160) NOT NULL,
    "Description" character varying(4000) NOT NULL,
    "Type" integer NOT NULL,
    "AddressLine" character varying(300) NOT NULL,
    "Suburb" character varying(200) NOT NULL,
    "Postcode" character varying(20) NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "ContactEmail" character varying(320),
    "ParkingInfo" character varying(1000) NOT NULL DEFAULT '',
    "TransitInfo" character varying(1000) NOT NULL DEFAULT '',
    "IsIdentityVerified" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_venues" PRIMARY KEY ("Id")
);

CREATE TABLE rooms (
    "Id" uuid NOT NULL,
    "VenueId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(160) NOT NULL,
    "Description" character varying(4000) NOT NULL,
    "Capacity" integer NOT NULL,
    "PricePerHour" numeric(10,2),
    "Currency" character varying(3) NOT NULL,
    "HouseRules" character varying(4000) NOT NULL,
    "Status" integer NOT NULL,
    "Amenities" integer NOT NULL,
    "AccessibilityFeatures" integer NOT NULL,
    "AcceptedActivityTypes" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_rooms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_rooms_venues_VenueId" FOREIGN KEY ("VenueId") REFERENCES venues ("Id") ON DELETE CASCADE
);

CREATE TABLE room_photos (
    "Id" uuid NOT NULL,
    "RoomId" uuid NOT NULL,
    "Url" character varying(1000) NOT NULL,
    "Caption" character varying(500),
    "IsPrimary" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    CONSTRAINT "PK_room_photos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_room_photos_rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES rooms ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_analytics_events_EventType_OccurredAtUtc" ON analytics_events ("EventType", "OccurredAtUtc");
CREATE INDEX "IX_room_photos_RoomId_SortOrder" ON room_photos ("RoomId", "SortOrder");
CREATE INDEX "IX_rooms_Status" ON rooms ("Status");
CREATE UNIQUE INDEX "IX_rooms_VenueId_Slug" ON rooms ("VenueId", "Slug");
CREATE INDEX "IX_venues_Latitude_Longitude" ON venues ("Latitude", "Longitude");
CREATE UNIQUE INDEX "IX_venues_Slug" ON venues ("Slug");
--rollback DROP TABLE room_photos;
--rollback DROP TABLE rooms;
--rollback DROP TABLE venues;
--rollback DROP TABLE analytics_events;
